kafka:
  bootstrap-servers: localhost:9092
  topic:
    name: vexchange 
gstreamer:
  pipe: ksvideosrc ! capsfilter caps=video/x-raw,width=640,height=480,framerate=30/1 ! videoconvert ! x264enc bitrate=15000 byte-stream=true
  